### ISSUE TITLE
Library Error: Android_HCE

### ISSUE THREAD

**Issue by ConorOD** [Seeed-Studio/PN532#40]
This is my error

`C:\Program Files\Arduino\libraries\PN532\emulatetag.cpp:49:16: error: expected identifier before numeric constant`

`C:\Program Files\Arduino\libraries\PN532\emulatetag.cpp:49:16: error: expected '}' before numeric constant`

`C:\Program Files\Arduino\libraries\PN532\emulatetag.cpp:49:16: error: expected unqualified-id before numeric constant`

`C:\Program Files\Arduino\libraries\PN532\emulatetag.cpp:49:31: error: expected declaration before '}' token`

**Comment by xiongyihui** [comment]
Which version of Arduino IDE do you use? No error in v1.0.5 and v1.6.4.

**Comment by ConorOD** [comment]
Ah, I was using 1.6.6 works fine on 1.6.4

thanks very much

**Comment by ConorOD** [comment]
So I fixed the error mentioned above, but when I try to upload it to my board (intel galilleo) i get the same error again, is it possibly a problem with my board?

**Comment by zapper9595** [comment]
Hi @ConorOD , not sure if your problem is solved. I'm currently facing the same problem. Do share if you did, thanks.

**Comment by ConorOD** [comment]
Hey @zapper9595 I'm not sure what I did, I will try to find the file and see if I can remember

**Comment by Pillar1989** [comment]
I'll close the question and open it again if you need to discuss it later
